name: coffee-demo
version: git
summary: Coffee Demo
description: Brew coffee
grade: stable
confinement: strict
base: core18

architectures:
  - build-on: arm64
  - build-on: amd64

slots:
  # for GtkApplication registration
  coffee-demo:
    interface: dbus
    bus: session
    name: com.canonical.coffee-demo

apps:
  daemon:
    daemon: simple
    restart-condition: always
    environment:
      LC_ALL: en_UK.UTF-8
      LIBGL_ALWAYS_SOFTWARE: 1
    command-chain:
      - bin/run-daemon
      - bin/wayland-launch
    command: bin/coffee_demo
    extensions: [flutter-master]
    plugs:
      - opengl
      - wayland
      - network

  coffee-demo:
    command: bin/coffee_demo
    extensions: [flutter-master]
    plugs:
      - opengl
      - network

parts:
  coffee-demo:
    source: .
    plugin: flutter
  mir-kiosk-snap-launch:
    plugin: dump
    source: https://github.com/MirServer/mir-kiosk-snap-launch.git
    override-build:  $SNAPCRAFT_PART_BUILD/build-with-plugs.sh opengl wayland network
    stage-packages:
      - inotify-tools

  assets:
    plugin: nil
    stage-packages:
    - dmz-cursor-theme
    - fonts-dejavu
    - fonts-freefont-ttf
    - fonts-ubuntu

layout:
  /usr/share/fonts:
    bind: $SNAP/usr/share/fonts
  /etc/fonts:
    bind: $SNAP/etc/fonts
  /usr/share/icons:
    bind: $SNAP/usr/share/icons
